// packages/typst.angular/projects/typst.angular/src/lib/typst.document.component.ts
import { Component, ElementRef, Input, ViewChild } from '@angular/core';
import { withGlobalRenderer } from '@jchoi2x/typst.ts/contrib/global-renderer';
import * as typst from '@jchoi2x/typst.ts';

let moduleInitOptions: typst.InitOptions = {
  beforeBuild: [],
  getModule: () => '/assets/typst-ts-renderer/pkg/typst_ts_renderer_bg.wasm',
};

@Component({
  standalone: false, // this is now required when using NgModule
  selector: 'typst-document',
  templateUrl: `./typst.document.component.html`,
  styleUrls: [`./typst.document.component.css`],
})
export class TypstDocumentComponent {
  _artifact: Uint8Array = new Uint8Array(0);
  @ViewChild('typst_app') typst_app?: ElementRef<HTMLDivElement>;

  @Input() fill: string = '#ffffff';

  @Input() format = 'vector' as const;

  @Input()
  set artifact(artifact: Uint8Array) {
    this._artifact = artifact;
    this.applyArtifact();
  }

  get artifact(): Uint8Array {
    return this._artifact;
  }

  constructor() {}

  applyArtifact() {
    if (this.typst_app?.nativeElement) {
      const displayDiv = this.typst_app?.nativeElement;
      if (this.artifact?.length) {
        const doRender = (renderer: typst.TypstRenderer) => {
          renderer.render({
            artifactContent: this.artifact,
            format: 'vector',
            backgroundColor: this.fill,
            container: displayDiv,
            pixelPerPt: 3,
          });
          return;
        };

        /// render after init
        withGlobalRenderer(typst.createTypstRenderer, moduleInitOptions, doRender);
      } else {
        displayDiv.innerHTML = '';
      }
    }
  }

  static setWasmModuleInitOptions(opts: typst.InitOptions) {
    moduleInitOptions = opts;
  }
}

// packages/typst.react/src/lib/TypstDocument.tsx
import { useRef, useEffect } from 'react';
import { withGlobalRenderer } from '@jchoi2x/typst.ts/dist/esm/contrib/global-renderer.mjs';
import * as typst from '@jchoi2x/typst.ts';
import htmlLayerCss from './typst.css?inline';

// const withGlobalRenderer = (...args: any[]) => {
//   void(args);
//   return undefined;
// };

export interface TypstDocumentProps {
  fill?: string;
  artifact: Uint8Array;
  // todo: add vector format
  format?: 'json';
}

let moduleInitOptions: typst.InitOptions = {
  beforeBuild: [],
  getModule: () => '/node_modules/@jchoi2x/typst-ts-renderer/pkg/typst_ts_renderer_bg.wasm',
};

export const TypstDocument = ({ fill, artifact, format }: TypstDocumentProps) => {
  const displayDivRef = useRef<HTMLDivElement>(null);
  const getDisplayLayerDiv = () => {
    return displayDivRef?.current;
  };

  useEffect(() => {
    const doRender = (renderer: typst.TypstRenderer) => {
      const divElem = getDisplayLayerDiv();
      if (!divElem) {
        return;
      }

      return renderer.render({
        artifactContent: artifact,
        format: 'vector',
        backgroundColor: fill,
        container: divElem,
        pixelPerPt: 3,
      });
    };

    /// get display layer div
    const divElem = getDisplayLayerDiv();
    if (!divElem) {
      return;
    }

    /// we allow empty artifact
    if (!artifact?.length) {
      divElem.innerHTML = '';
      return;
    }

    /// render after init
    withGlobalRenderer(typst.createTypstRenderer, moduleInitOptions, doRender);
  }, [displayDivRef, fill, artifact, format]);

  return (
    <div>
      {/* todo: remove this embedded css */}
      <style>{htmlLayerCss}</style>
      <div className="typst-app" style={{ height: '0' }} ref={displayDivRef}></div>
    </div>
  );
};

/**
 * @deprecated since version v0.6.0
 */
TypstDocument.setWasmModuleInitOptions = (opts: typst.InitOptions) => {
  moduleInitOptions = opts;
};
